### PR TITLE
fix(pandas): update compatibility

### PR DESCRIPTION
**Pull request by sxcntqnt**
## Summary
- Update to the schema generation for Pandas Update Compatibility.

## Changes
- Instead of directly appending a dictionary to the DataFrame, create a new DataFrame (`new_row`) that contains the data to add.
- Use `pd.concat()` to concatenate the original DataFrame (`frame`) with the new DataFrame (`new_row`).
  - The `ignore_index=True` parameter ensures the index is reset after concatenation.

### CODE REVIEW

**Comment by kiran94** [comment]
Hello, thank you for the contribution :) 

I ran the CI and it was failing but this wasn't due to your change. It's just because it's been a while since that CI has run and there have been some changes in the ecosystem which I detailed and fixed in https://github.com/kiran94/dgraphpandas/pull/29 and https://github.com/kiran94/dgraphpandas/pull/30

That is all fixed now, the main branch CI is passing and the latest release from my changes were published https://github.com/kiran94/dgraphpandas/actions/runs/12389882253/job/34583796574. Could you update your fork with the latest changes so we can try again?

Could you also update the version in this PR, you can find it here: https://github.com/kiran94/dgraphpandas/blob/7189ada53bbb92ba65f23919546bc0ea8b3afe97/dgraphpandas/__init__.py#L2

Also if you don't mind, I usually have the PR titles and subsequent squashed commits following conventional commit. You can see some examples here https://github.com/kiran94/dgraphpandas/pulls?q=is%3Apr+is%3Aclosed

**Comment by sxcntqnt** [comment]
made the update to my fork it should be ready  for the pull now

**Comment by kiran94** [comment]
> made the update to my fork it should be ready for the pull now

Thanks! CI is passing now 

> Could you also update the version in this PR, you can find it here:

Could you also bump the version please :)

**Comment by sxcntqnt** [comment]
Is everything okay now

**Comment by kiran94** [comment]
> Is everything okay now

Once you update the version as I mentioned in https://github.com/kiran94/dgraphpandas/pull/28#issuecomment-2550835075 on this branch then I am happy to merge 

The version needs to be bumped so when it's deployed to pypi, it's deployed as a new version. For this change `0.1.5` should be good

**Comment by sxcntqnt** [comment]
Still new to this whole github thing.Thanks for the headsup.

**Comment by kiran94** [comment]
> Still new to this whole github thing.Thanks for the headsup.

No problem :) thanks again for the contribution 

Your change has been published as `v0.1.5`: 

* https://github.com/kiran94/dgraphpandas/releases/tag/v0.1.5
* https://github.com/kiran94/dgraphpandas/actions/runs/12392105164/job/34590565198
* https://pypi.org/project/dgraphpandas/#history

**Pull request merged**
